flags: {}
packages:
- .
- location: ../hs-web3
  extra-dep: true
allow-newer: true
extra-deps:
- equational-reasoning-0.5.1.0
- ghc-typelits-presburger-0.2.0.0
- sized-0.3.0.0
- type-natural-0.8.0.0
- ethereum-rlp-0.1.0
resolver: lts-11.1
