flags: {}
packages:
- .
allow-newer: true
extra-deps:
- equational-reasoning-0.5.1.0
- ghc-typelits-presburger-0.2.0.0
- sized-0.3.0.0
- type-natural-0.8.0.0
- ethereum-rlp-0.1.0
- optparse-applicative-0.14.2.0
- ../hs-web3
# - git: https://github.com/Daolab/hs-web3.git
#   commit: 85c555509d9a68ccda78ad67fbca18cd89961cd8
resolver: lts-11.1
