version: 2
jobs:
  build:
    docker:
      - image: ccistaging/rust:1-node
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            wget https://github.com/commercialhaskell/stack/releases/download/v1.6.3/stack-1.6.3-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
            mkdir /tmp/stack/
            tar -xvzf /tmp/stack.tar.gz -C /tmp/stack/
            sudo mv /tmp/stack/stack-1.6.3-linux-x86_64/stack /usr/bin/stack
      - restore_cache:
          keys:
            - deps3-{{ .Branch }}-{{ .Revision }}
            - deps3-{{ .Branch }}-stack-{{ checksum "stack.yaml" }}-cargo-{{ checksum "Cargo.lock" }}
            - deps3-{{ .Branch }}-
      - run:
          name: Setup
          command: |
            sudo apt-get -y install gcc
            sudo apt-get -y install libgmp3-dev
            stack setup --no-terminal
            curl -sL https://deb.nodesource.com/setup_9.x | sudo bash -
            sudo apt-get -y install nodejs
            # sudo npm install -g ganache-cli
      - run:
          name: Seupt SolC
          command: |
            sudo add-apt-repository ppa:ethereum/ethereum
            sudo apt-get update
            sudo apt-get install solc
      - run:
          name: Install Parity
          command: |
            curl -sL https://releases.parity.io/v2.0.6/x86_64-unknown-linux-gnu/parity -o parity
            chmod 755 parity
      - run:
          name: Start local Ethereum network
          # command: ganache-cli
          command: |
            # we need to run parity once to set up the accounts and keys
            # this only needs to be active for a few seconds (hence timeout)
            timeout 5 ./parity --config dev || true
            # We then run parity properly, now unlocking the previously setup
            # account
            ./parity --config dev --force-sealing --reseal-min-period 2000 --reseal-max-period 10000 --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password empty.txt
          background: true
      - run:
          name: Wait for Parity startup
          command: sleep 10
      - run:
          name: Build Haskell Component
          command: |
            stack build Cabal --no-terminal
            stack build --no-terminal --test --no-run-tests
      - run:
          name: Build Rust Component
          command: |
            cargo build
      - save_cache:
          key: deps3-{{ .Branch }}-stack-{{ checksum "stack.yaml" }}-cargo-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.stack"
            - ".stack-work"
      - run:
          name: Test Haskell Component
          command: |
            stack test --no-terminal
      - run:
          name: Test Rust Component
          command: |
            make contracts
            cargo test
