version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            wget https://github.com/commercialhaskell/stack/releases/download/v1.6.3/stack-1.6.3-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
            mkdir /tmp/stack/
            tar -xvzf /tmp/stack.tar.gz -C /tmp/stack/
            sudo mv /tmp/stack/stack-1.6.3-linux-x86_64/stack /usr/bin/stack
      - restore_cache:
          keys:
            - deps3-{{ .Branch }}-{{ .Revision }}
            - deps3-{{ .Branch }}-
      - run:
          name: Setup
          command: |
            sudo apt-get -y install gcc
            sudo apt-get -y install libgmp3-dev
            stack setup --no-terminal
            curl -sL https://deb.nodesource.com/setup_9.x | sudo bash -
            sudo apt-get -y install nodejs
            # sudo npm install -g ganache-cli
            curl -sL https://releases.parity.io/v2.0.6/x86_64-unknown-linux-gnu/parity
      - run:
          name: Start local Ethereum network
          # command: ganache-cli
          command: ./parity --config dev --force-sealing --reseal-min-period 2000 --reseal-max-period 10000 --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea7
2 --password empty.txt
          background: true
      - run:
          name: Build
          command: |
            stack build Cabal --no-terminal
            stack build --no-terminal --test --no-run-tests
      - save_cache:
          key: deps3-{{ .Branch }}-
          paths:
            - "~/.stack"
            - ".stack-work"
      - run:
          name: Test
          command: |
            stack test --no-terminal

